# Use minimal environment, everything is in docker containers.
language: minimal
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker version
  - docker-compose version
  - docker pull golang:1.12
  - docker pull php:7.2-fpm
  - docker run -it --rm -v "$PWD":/usr/src/dr -w /usr/src/dr golang:1.12 go build -v
  - sudo ln -s $PWD/docker-relay /usr/local/bin/go
  - sudo ln -s $PWD/docker-relay /usr/local/bin/php
  - cp test/travis.docker-relay.yml $HOME/.docker-relay.yml

script:
  - go version
  - cd test 
  - docker-compose up -d
  - ./check
  - PHP_EXIT=exception ./check; if [ $? -ne 255 ]; then false; fi
