# Use minimal environment, everything is in docker containers.
language: minimal
sudo: 'required'

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - docker version
  - docker-compose version
  - docker pull golang:1.12
  - docker pull php:7.2-fpm

script:
  - docker run -it --rm -v "$PWD":/usr/src/dr -w /usr/src/dr golang:1.12 go version
  - cd test 
  - docker-compose up -d
  - docker-compose exec php ./check
  - docker-compose exec -e TEST_FAIL=exception php ./check; if [ $? -ne 255 ]; then exit 1; fi
